### ISSUE TITLE
graphic corruption and/or hard locking

### ISSUE THREAD

**Issue by pixelr0** [lotharsm/devilutionx-snapcraft#1]
installed version 
devilutionx                      1.0.1-174-g0fddb655            22    latest/edge       lserramari          -

~$ devilutionx 
ERROR: ld.so: object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (failed to map segment from shared object): ignored.
libGL error: MESA-LOADER: failed to retrieve device information
libGL error: Version 4 or later of flush extension not found
libGL error: failed to load driver: i915
libGL error: MESA-LOADER: failed to retrieve device information
INFO: SFileOpenFile: Not found: ui_art\title.pcx
INFO: SFileOpenFile: Not found: ui_art\black.pcx
intel_do_flush_locked failed: Input/output error

and then all i see is graphic corruption and/or the PC hard locks

**Comment by pixelr0** [comment]
apparently https://github.com/diasurgical/devilutionX does the same thing.. so it's not a snap thing 

for the snap i have /home/pixel/snap/devilutionx/current/.local/share/diasurgical/devilution//home/pixel/snap/devilutionx/current/.local/share/diasurgical/devilution/diabdat.mpq 

but doesn't work. I hear the intro sound but then the game locks.

**Comment by lotharsm** [comment]
Thanks for your report! That's somewhat weird since I can't replicate the issues with the snap on 18.04 and 20.04, the current code compiled directly from the devilutionX master branch works for me too. A corrupt diabdat.mpq won't lead to a crash, you should see an error message then.

Looking at the error message, I think it's an issue with the i915 driver, seems that it doesn't like to communicate with OpenGL...

**Comment by lotharsm** [comment]
Oh, btw, which Ubuntu version are you using?

**Comment by pixelr0** [comment]
20.04

**Comment by lotharsm** [comment]
Can you try installing the package `gtk3-nocsd` on your machine and check if the builds from the devilutionx start working? The snap will most likely remain broken until I add the package to the snapcraft.yaml, even if the build from git starts working.

**Comment by pixelr0** [comment]
gtk3-nocsd is already the newest version (3-1ubuntu1).
i already have it installed. i'm using Unity7 session instead of the default Gnome Shell

**Comment by lotharsm** [comment]
I'll try to fix the snap by explicity adding the path to the LD_PRELOAD environment variable and by providing the gtk3-nocsd package in the snap, maybe we can fix the snap at least :)

**Comment by lotharsm** [comment]
Hold on, looks like the snap is broken in general, investigating.

**Comment by pixelr0** [comment]
take your time :D it's in the edge channel anyway. people are aware that stuff in the edge channel might not work (hence the edge channel) :P 

and the corruption/locking part is not this snap's fault. it's a Linux thing. i get the same result with the  executable from github by not giving the right path to diabdat.mpq

**Comment by lotharsm** [comment]
Regarding the snap, it was my fault, see https://github.com/lotharsm/devilutionx-snapcraft/commit/f4cc32e3d9a29abab6e8172a4617a55286ac3edd.

A rebuild of the snap is currently in progress, so please try to `snap refresh devilutionx` in about 30 minutes. Thanks a lot for reporting this issue!

**Comment by pixelr0** [comment]
refreshed, works fine now :D THANKS

snap refresh
snap-store (stable/ubuntu-20.04) 3.36.0-80-g208fd61 from Canonical✓ refreshed
devilutionx (edge) 1.0.1-174-g0fddb655 from Lothar Serra Mari (lserramari) refreshed

**Comment by lotharsm** [comment]
Thanks a lot for your feedback :)
