### ISSUE TITLE
Update snap version to 1.2.1

### ISSUE THREAD

**Issue by BenPutnam** [lotharsm/devilutionx-snapcraft#4]
Could the snap package be updated to devilutionx version 1.2.1?

**Comment by lotharsm** [comment]
Thanks for the heads-up, I'll look into it. Looks like autobuilding the snap currently fails due to my crude patch to show the correct path in the error message if DIABDAT.MPQ is missing - I need to adapt it to the current codebase (or finally look on how to upstream it).

**Comment by lotharsm** [comment]
The current version 1.4.0 is now available in the `stable` channel.

**Comment by BenPutnam** [comment]
> The current version 1.4.0 is now available in the `stable` channel.

Thank you.
