### ISSUE TITLE
Update to 1.5.0

### ISSUE THREAD

**Issue by seaben** [lotharsm/devilutionx-snapcraft#6]
Hi!
Could you kindly update to version 1.5.0? Thank you!
And thanks for maintaining a snap version! Much appreciated.

**Comment by pparidans** [comment]
Hi @lotharsm any news on that regard ?
I'd be glad to help if needed.

**Comment by lotharsm** [comment]
I currently have no plans to work on this, sorry. I might pick this up at a later point in time.
